### ISSUE TITLE
Proposal for Github Issues and PR templates

### ISSUE THREAD

**Issue by pragmaticivan** [doomspork/elixir-school#127]
I think it's a good time to provide a good template for Issues and PR

**Comment by pragmaticivan** [comment]
#Proposal for ISSUES:
--------------------------------------------------------------------------------------------------------------
#### Description
A clear and concise description of what the issue is about.

#### Screenshots
![Downhill Windmills](http://i.giphy.com/KO8AG2EByqkFi.gif)

#### Files
A list of relevant files for this issue. This will help people navigate the project and offer some clues of where to start.

#### To Reproduce
If this issue is describing a bug, include some steps to reproduce the behavior.

#### Tasks
Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.
- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

**Comment by pragmaticivan** [comment]
# Proposal for Pull Request
----------------------------------------------------------------------------------------

## Proposed changes

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Types of changes

What types of changes does your code introduce to Elixir School?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have read the [CONTRIBUTING](/CONTRIBUTING.md) doc
- [ ] I have added necessary documentation (if appropriate)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

**Comment by pragmaticivan** [comment]
Extra info about the template system:
https://help.github.com/articles/creating-an-issue-template-for-your-repository/
https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/

**Comment by pjhampton** [comment]
@pragmaticivan Ahh, @doomspork and I were chatting about this over slack the other day and we agreed it was a good idea. We would need a Lesson Suggestion one as well. Do you want to take this forward or do you want to leave this with me?

**Comment by pragmaticivan** [comment]
I think we first need to agree with the templates, so would be good a generic one, including some optional checklist in case of lessons. Do you guys can add some suggestions here in this issue?

**Comment by pragmaticivan** [comment]
The one I posted above are generic, and maybe we can add more checklists related to lessons and new languages.

**Comment by doomspork** [comment]
This is a great start @pragmaticivan!  As @pjhampton mentioned, we were recently discussing this on Slack.  Let me think about this and I'll come up with some ideas and feedback.

**Comment by pragmaticivan** [comment]
Cool :D

**Comment by doomspork** [comment]
@pragmaticivan I haven't forgotten about these!  I'll make time this week to get back to you with some feedback.

**Comment by pjhampton** [comment]
Any movement on these guys? @doomspork @pragmaticivan

**Comment by doomspork** [comment]
@pjhampton I haven't the time to sit down and put together something more specific to our needs.  It's on my list

**Comment by doomspork** [comment]
I don't think Issues are used enough to worry about a template so I focused on the PR template.  I don't want filling out a form to block people from contributing, so I kept it short and sweet.  

Here's my first stab at it:

---

## Types of changes

What types of changes does your code introduce to Elixir School? _Put an `x` in the boxes that apply_

- [ ] Fix (correcting visual bugs, spelling, or grammar)
- [ ] Translation (translation of an existing lesson)
- [ ] New Lesson (brand new content)

## Comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

- [ ] I have read the [CONTRIBUTING](/CONTRIBUTING.md) doc

**Comment by pragmaticivan** [comment]
Maybe `I have added necessary documentation (if appropriate)` is a good one to have, it happened in the case of adding description data into an array for new languages. And by the end there was no documentation for that.

**Comment by doomspork** [comment]
I'm still on the fence but I'm leaning towards shelving the Issues/PR templates for the time being.  I'm not sure there is much to be gained and they don't seem to be working out on other projects.
